/-
Copyright (c) 2026 Richard Osborn. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Richard Osborn
-/
module

public import Mathlib.Algebra.Group.Subgroup.Lattice
public import Mathlib.Order.CompactlyGenerated.Basic

/-!
# Compact elements of the subgroup lattice

The subgroup generated by a single element is a compact element of the subgroup lattice.
Consequently, membership in a supremum `⨆ i, H i` is witnessed by a finite subfamily.
This mirrors the corresponding results for submodules in `Mathlib/LinearAlgebra/Span/Basic.lean`
and `Mathlib/LinearAlgebra/Finsupp/Span.lean`.
-/

@[expose] public section

namespace Subgroup

variable {G : Type*} [Group G]

/-- The subgroup generated by one element is a compact element of the subgroup lattice. -/
@[to_additive /-- The additive subgroup generated by one element is a compact element of the
additive subgroup lattice. -/]
theorem isCompactElement_closure_singleton (g : G) :
    IsCompactElement (closure {g} : Subgroup G) := by
  rw [CompleteLattice.isCompactElement_iff_le_of_directed_sSup_le]
  intro d hemp hdir hsup
  have : g ∈ sSup d := hsup (subset_closure (Set.mem_singleton g))
  obtain ⟨K, hKd, hgK⟩ := (mem_sSup_of_directedOn hemp hdir).mp this
  exact ⟨K, hKd, by rwa [closure_le, Set.singleton_subset_iff]⟩

@[to_additive]
theorem exists_finset_of_mem_iSup {ι : Type*} (H : ι → Subgroup G) {g : G}
    (hg : g ∈ ⨆ i, H i) : ∃ s : Finset ι, g ∈ ⨆ i ∈ s, H i := by
  have hle : (closure {g} : Subgroup G) ≤ ⨆ i, H i := by
    rwa [closure_le, Set.singleton_subset_iff, SetLike.mem_coe]
  obtain ⟨s, hs⟩ := CompleteLattice.IsCompactElement.exists_finset_of_le_iSup (Subgroup G)
    (isCompactElement_closure_singleton g) H hle
  exact ⟨s, by simpa [closure_le] using hs⟩

/-- `Subgroup.exists_finset_of_mem_iSup` as an `iff`. -/
@[to_additive /-- `AddSubgroup.exists_finset_of_mem_iSup` as an `iff`. -/]
theorem mem_iSup_iff_exists_finset {ι : Type*} {H : ι → Subgroup G} {g : G} :
    (g ∈ ⨆ i, H i) ↔ ∃ s : Finset ι, g ∈ ⨆ i ∈ s, H i :=
  ⟨exists_finset_of_mem_iSup H, fun ⟨_, hs⟩ =>
    iSup_mono (fun i => (iSup_const_le : _ ≤ H i)) hs⟩

end Subgroup
